FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY /package*.json ./
RUN npm install

COPY /prisma ./prisma/
RUN npx prisma generate

COPY . .

EXPOSE 3001

CMD [ "npm", "run", "dev" ]